# Generated by Django 5.1.1 on 2024-09-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transcriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="transcription",
            table="transcriptions",
        ),
    ]
