# Generated by Django 5.1.1 on 2024-09-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcriptions", "0002_alter_transcription_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transcription",
            name="sentiment_score",
        ),
        migrations.RemoveField(
            model_name="transcription",
            name="speakers",
        ),
        migrations.RemoveField(
            model_name="transcription",
            name="transcription",
        ),
        migrations.RemoveField(
            model_name="transcription",
            name="translation",
        ),
        migrations.AddField(
            model_name="transcription",
            name="abusive_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transcription",
            name="agent_sentiment_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transcription",
            name="agent_transcription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transcription",
            name="agent_translation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transcription",
            name="contains_financial_info",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transcription",
            name="customer_sentiment_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transcription",
            name="customer_transcription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transcription",
            name="customer_translation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="date_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
